# Generated by Django 5.0.6 on 2024-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_post_cat_post_image_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
