# Generated by Django 5.0.6 on 2024-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_subplan_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='no_of_post',
            field=models.IntegerField(default=1),
        ),
    ]
